### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by di**
~~Also switch to SSH for cloning.~~

### CODE REVIEW

**Comment by bduggan** [comment]
Why switch to ssh?  http seems a bit more natural to me in this context.

**Comment by di** [comment]
> Why switch to ssh? http seems a bit more natural to me in this context.

Simply because cloning with HTTPS requires jumping through hoops for users with 2FA enabled. But I'm fine w/ dropping this commit!

**Comment by bduggan** [comment]
Interesting! I wouldn't think you'd have to do any auth to clone via HTTP -- that's very strange.

**Comment by bduggan** [comment]
It would be nice to avoid auth (or even git) being a requirement, so maybe something like this would be better:
```
curl -vL https://github.com/promptworks/aws-secrets/archive/0.01.tar.gz | tar xv -
```
(where we bump the version for each release)

**Comment by bduggan** [comment]
Looks good, thanks.

**Pull request merged**
